---
title: "Cooper Gant"
output: html_document
date: "2025-05-01"
---

::: {style="text-align: center; color: #008000;"}
# Stuck in a revenue ditch: Arkansas registered electric vehicle yearly fee grows, gas tax revenue drops

A data analysis

(ver May 12, 2025)
:::

<br>

::: {style="font-weight:bold;"}
``` markdown
Cooper Gant, June 2, 2025 
```
:::

<!-- 
Use for link: <a href="link_here" target="_new">Text in here</a>
-->

Since 2019, Electric vehicle drivers in Arkansas have [paid a yearly fee](https://www.arkansasonline.com/news/2019/sep/29/new-fuel-taxes-kick-in-tuesday-for-stat/#:~:text=The%20state's%20excise%20tax%20on,to%20Arkansas%2C%20also%20starting%20Tuesday.) of \$200 (fully electric), \$100 (hybrid) or \$50 (hybrid plug-in) for their vehicles. The legislation was written to cover a portion of the [“lost gas tax” revenue that would have otherwise been gained from them](https://afdc.energy.gov/laws/all?state=AR#:~:text=Hybrid%20Electric%20Vehicle%20(HEV)%20and,Highway%20and%20Transportation%20Department%20Fund.) at the pump. In the last five years, the revenue gained from this has continued to grow lockstep to the rise of electric vehicles in the Natural State, whereas the year-to-year motor sales tax has plateaued in recent months.

Scott Hardin, spokesperson for the Arkansas Department of Finance, said the organization has garnered \$11,810,093.88 since 2019 in collected fees from electric vehicle drivers. Thus far, hybrid vehicle drivers have paid the most with \$7,764,048.40, fully electric drivers follow at just over half the amount with \$3,687,990.92 and plug-in hybrid electric drivers paid \$358,054.56 in the last six years.

<iframe title="Charging stations per one electric vehicle (2023)" aria-label="Map" id="datawrapper-chart-A0xRB" src="[https://datawrapper.dwcdn.net/A0xRB/1/"](https://datawrapper.dwcdn.net/A0xRB/1/%22) scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="400" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r,i=0;r=e[i];i++)if(r.contentWindow===a.source){var d=a.data["datawrapper-height"][t]+"px";r.style.height=d}}}))}();

</script>

\

<iframe title="Which state had the most electric vehicles in 2023?" aria-label="Map" id="datawrapper-chart-QcoN1" src="https://datawrapper.dwcdn.net/QcoN1/1/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="400" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r,i=0;r=e[i];i++)if(r.contentWindow===a.source){var d=a.data["datawrapper-height"][t]+"px";r.style.height=d}}}))}();
</script>

Hardin said that although the ADFA does not have the specific yearly amounts, the revenue has continued to climb year-to-year since 2019. The number of registered fully-electric vehicle drivers in Arkansas has increased from 781 to 8,807, and the number of hybrid vehicles has climbed from 13,861 to 48,797. 

This mirrors national trends, with a major boost to the industry taking place in the early 2020’s. In 2023, [Arkansans drove the 10th-lowest electric vehicle count in the nation,](https://afdc.energy.gov/data/10962) but have steadily increased their green presence in the last decade.

<iframe title="Which state had the most electric vehicles in 2023?" aria-label="Map" id="datawrapper-chart-QcoN1" src="[https://datawrapper.dwcdn.net/QcoN1/1/"](https://datawrapper.dwcdn.net/QcoN1/1/%22) scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="400" data-external="1"\>\</iframe\>\<script type="text/javascript"\>!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r,i=0;r=e[i];i++)if(r.contentWindow===a.source){var d=a.data["datawrapper-height"][t]+"px";r.style.height=d}}}))}();

</script>

The motor fuels sales tax, contrary to its earth-friendly counterpart, has continued to increase year to year, but dropped in the last few months. According to public records, the revenue hit its highest peak in the last six years in 2023, but dropped to \$603 million in 2024 – the lowest collected year since 2020. 

\<iframe title="Arkansas motor fuel sales tax" aria-label="Interactive line chart" id="datawrapper-chart-ZnKCT" src="[https://datawrapper.dwcdn.net/ZnKCT/1/"](https://datawrapper.dwcdn.net/ZnKCT/1/%22) scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="400" data-external="1"\>\</iframe\>\<script type="text/javascript"\>!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r,i=0;r=e[i];i++)if(r.contentWindow===a.source){var d=a.data["datawrapper-height"][t]+"px";r.style.height=d}}}))}();

\</script\>

However, there is notable overall growth from the tax’s revenue since 2015, with Q3 of 2023 having the highest quarterly total.  

\<iframe title="Charging stations per one electric vehicle (2023)" aria-label="Map" id="datawrapper-chart-A0xRB" src="[https://datawrapper.dwcdn.net/A0xRB/1/"](https://datawrapper.dwcdn.net/A0xRB/1/%22) scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="400" data-external="1"\>\</iframe\>\<script type="text/javascript"\>!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r,i=0;r=e[i];i++)if(r.contentWindow===a.source){var d=a.data["datawrapper-height"][t]+"px";r.style.height=d}}}))}();

\</script\>\
Despite the Natural State’s growing number of registered electric vehicles, Arkansas remains one of the least friendly to electric vehicle drivers. [The Department of Energy’s official data base reported](https://afdc.energy.gov/fuels/electricity-locations#/analyze) Arkansas as the ninth-lowest rate of electric vehicle charging stations per vehicle in 2023. \

\<iframe title="Charging stations per one electric vehicle (2023)" aria-label="Map" id="datawrapper-chart-A0xRB" src="[https://datawrapper.dwcdn.net/A0xRB/1/"](https://datawrapper.dwcdn.net/A0xRB/1/%22) scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="400" data-external="1"\>\</iframe\>\<script type="text/javascript"\>!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r,i=0;r=e[i];i++)if(r.contentWindow===a.source){var d=a.data["datawrapper-height"][t]+"px";r.style.height=d}}}))}();

\</script\>

As of June 2025, Arkansas has now garnered a total of [396 charging stations and 1,039 outlets](https://afdc.energy.gov/stations#/analyze?country=US&fuel=ELEC&ev_levels=all&access=public&access=private&region=US-AR), but there are still parts of the state that lack sufficient charging ports. Most of the chargers’ locations correlate to population density, highlighting an abundance in central and northwest Arkansas with few accessible in the southern region.

\*insert graphic that is not finished yet, having to manually plug in longitude and latitude of a bunch of locations\*\
TKTKTKTK (doing calculations on traveling in Arkansas, was stopped today by having to do the math on finance and re-direct the project)

\*graphic mapping Arkansas\*

(room for interviews explaining the situation ).\

\*There is a wide assortment of sources that can comment on this story. Scott Hardin of the Arkansas DFA, small-town business owners that manage charging stations, any of the environmental dynamics program staff at the University of Arkansas at Fayetteville, current ARDOT director Jared Wiley, and former ARDOT director Lorie Tudor (she oversaw the organization during the time of the collected data pool from 2019-2023).\*
